version: '3'
volumes:
  mysql_data:
services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "8008:3000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: chatapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
      restart: always
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_PORT: 3306
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
      - ./backend:/app
      expose:
        - "8080"
      ports:
        - "8082:8082"
      depends_on:
       - mysql